---
title: "Original Research Articles"
---

## Statistical Methodology {#stat-methodology}
-  Kyomuhangi, I., **<u>Giorgi, E.</u>** (2022). *A threshold-free approach with age-dependency for estimating malaria seroprevalence.* Malaria Journal. https://doi.org/10.1371/journal.pone.0262145



-  Macharia, P., Ray, N., Gitonga, C. W., Snow, R. W., **<u>Giorgi, E.</u>** (2022). *Combining school-catchment area models with geostatistical models for analysing school survey data from low-resource settings: inferential benefits and limitations.* Spatial statistics.   https://doi.org/10.1016/j.spasta.2022.100679


-  **<u>Giorgi, E.</u>**, Fronterre, C., Macharia, P., Alegana, V., Snow, R., Diggle, P. (2021) *Model building and assessment of the impact of covariates for disease prevalence mapping in low-resource settings: to explain and to predict.* Journal of the Royal Society Interface. 18:20210104.   http://doi.org/10.1098/rsif.2021.0104

-  Kyomuhangi, I., **<u>Giorgi, E.</u>** (2021) *A unified and flexible modelling framework for the analysis of malaria serology data.* Epidemiology \& Infection. doi:10.1017/S0950268821000753


-  Johnson, O. O., Getherall, T., Knight, J., **<u>Giorgi, E.</u>** (2020) *A modelling framework for developing early warning systems of COPD emergency admissions.* Spatial and spatio-temporal epidemiology. doi: 10.1016/j.sste.2020.100392

-  Eyre, M. T., Carvalho-Pereira, T. S., Souza, F. N., Khalil, H., Hacker, K. P., Serrano, S., Taylor, J. P., Reis, M. G., Ko, A. J., Begon, M., Diggle, P. J., Costa, F., **<u>Giorgi, E.</u>** (2020) *A multivariate geostatistical framework for combining multiple indices of abundance for disease vectors and reservoirs: A case study of rattiness in a low-income urban Brazilian community.* Journal of the Royal Society Interface. doi:10.1098/rsif.2020.0398

-  Johnson, O. O., Diggle, P. J., **<u>Giorgi, E.</u>**, (2020). *Dealing with spatial misalignment to model the relationship between deprivation and life expectancy: A model-based geostatistical approach.* International Journal of Health Geographics.  DOI: 10.1186/s12942-020-00200-w


-  Kyomuhangi, I., Abeku, T. A., Kirby, M. J., Tesfaye, G.,**<u>Giorgi, E.</u>** (2020). *Understanding the effects of dichotomization of continuous outcomes on geostatistical inference.* Spatial Statistics. 00424, https://doi.org/10.1016/j.spasta.2020.100424.

-  Ejigu, B. A., Wencheko, E., Moraga, P., **<u>Giorgi, E.</u>**, (2020). *Geostatistical methods for modelling non-stationary patterns
in disease risk.* Spatial Statistics. doi:10.1016/j.spasta.2019.100397

-  Fronterre, C., Amoah, B., **<u>Giorgi, E.</u>**, Stanton, M., Diggle, P.J., *Design and analysis of elimination surveys for neglected tropical diseases.* (2020). Journal of Infectious Diseases. jiz554, https://doi.org/10.1093/infdis/jiz554


-  Milton, P., **<u>Giorgi, E.</u>**, Bhatt, S. (2019). *Spatial Analysis Made Easy with Linear Regression and Kernels.* Epidemics. DOI:10.1016/j.epidem.2019.100362 

-  Amoah, B., Diggle, P. J., **<u>Giorgi, E.</u>** (2019). *A geostatistical framework for combining data from multiple diagnostic tests.* Biometrics. doi:10.1111/biom.13142

-  Johnson, O. O., Diggle, P. J., **<u>Giorgi, E.</u>** (2019). *A spatially discrete approximation to log-Gaussian Cox processes for modelling aggregated disease count data.* Statistics in Medicine. doi:10.1002/sim.8339



-  Fronterre, C., **<u>Giorgi, E.</u>**, Diggle, P. J. (2018). *Geostatistical inference in the presence of geomasking: a composite-likelihood approach.* Spatial Statistics. DOI: 10.1016/j.spasta.2018.06.004



-  **<u>Giorgi, E.</u>**, Diggle, P. J., Snow, R. W., Noor, A. M. (2018). *Geostatistical methods for disease mapping and visualization using data from spatio-temporally referenced prevalence surveys.* International Statistical Review. https://doi.org/10.1111/insr.12268


-  **<u>Giorgi, E.</u>**, (2018). *On the goodness-of-fit of generalized linear geostistical models.* Spatial statistics. https://doi.org/10.1016/j.spasta.2018.01.002 


-  **<u>Giorgi, E.</u>**, Schlüter, D. K., Diggle, P. J. (2017). *Bivariate geostatistical modelling of the relationship between Loa loa prevalence and intensity of infection.* Environmetrics. doi:10.1002/ env.2447


-  **<u>Giorgi, E.</u>**, Diggle, P. J. (2017). *PrevMap: an R package for prevalence mapping.* Journal of Statistical Software. 78:1-29, doi: 10.18637/jss.v078.i08

-  Diggle, P. J., **<u>Giorgi, E.</u>** (2016). *Model-based geostatistics for prevalence mapping in low-resource settings (with discussion).* Journal of the American Statistical Association. 111:1096-1120

-  **<u>Giorgi, E.</u>**, Diggle, P. J. (2014). *On the inverse geostatistical problem of inference on missing locations.* Spatial statistics. 11:35-44 arXiv:1409.3408

-  **<u>Giorgi, E.</u>**, Sesay, S. S., Terlouw, D. J., Diggle, P. J. (2015). *Combining data from multiple spatially referenced prevalence surveys using generalized linear geostatistical models.* Journal of the Royal Statistical Society, Series A. 178:445-464 arXiv:1308.2790

-  **<u>Giorgi, E.</u>**, McNeil, A. J. (2014). *On the computation of multivariate scenario sets for the skew-t and generalized hyperbolic families.* Computational Statistics and Data Analysis. 100:205-220 arXiv:1402.0686

## Applications in Public Health {#public-health}

-  Puranik, A., Diggle, P. J., Odiere, M. R., Gass, K., Kepha, S., Okoyo, C.,  Mwandawiro, C., Wakesho, F., Omondi, W., Sultani, H. M., **<u>Giorgi, E.</u>**, *Understanding the impact of covariates on the classification of implementation units for soil-transmitted helminths control: A case study from Kenya.* BMC Medical Research Methodology, 24, 294 (2024). https://doi.org/10.1186/s12874-024-02420-1

-  Khaki, J.,  Macharia, P., **<u>Giorgi, E.</u>**, Benova, L., *Prevalence and determinants of double and triple burden of malnutrition among mother-child pairs in Malawi: a mapping and multilevel modelling study.* Pubblic Health Nutrition. Public Health Nutrition.  
2024;27(1):e241. doi:10.1017/S1368980024002064 

-  Soni, N., Eyre, M. T., Souza, F. N., Diggle, P. J., Ko, A. I., Begon, M., Pickup, R., Childs, J. E., Khalil, H., Carvalho-Pereira, T. S. A., Pertile, A. C., Carvalho, M., de Oliveira, D., Junior, N. N., **<u>Giorgi, E.</u>**$^*$, Costa, F.$^*$, *Disentangling the influence of reservoir abundance and pathogen shedding on zoonotic spillover of the Leptospira agent in urban informal settlements.* International Journal of Hygiene and Environmental Health. 12:1447592. doi: 10.3389/fpubh.2024.1447592 
$^*$These authors contributed equally.

-  Khaki, J.J, Meiring, J.E., Thindwa, D., Henrion, M.Y., Jere, T.M., Msuku, H., The STRATAA Consortium, Heyderman, R.S., Gordon, M. A., **<u>Giorgi, E.</u>** (2024). *Modelling Salmonella Typhi in Blantyre, Malawi, using point pattern methods.* Scientific Reports. 14, 17164.  https://doi.org/10.1038/s41598-024-66436-9

-  Barrett, C. L., Chiphwanya, J., Mkwanda, D., Matipula, D. E., Ndhlovu, P., Chaponda, L., Turner, J. D., **<u>Giorgi, E.</u>**, Betts, H., Martindale, S., Taylor, M. J., Read, J. M., Kelly-Hope, L. A. (2024).*The national distribution of lymphatic filariasis cases in Malawi using patient mapping and geostatistical modelling.* PLoS Neglected Tropical Diseases.  https://doi.org/10.1371/journal.pntd.0012056

-  Mountain, R., Knight, J., Heys, K., **<u>Giorgi, E.</u>**$^*$, and Gatheral$^*$, T. (2024). *Spatio-temporal modelling of referrals to outpatient respiratory clinics in the integrated care system of the Morecambe Bay area.* BMC Health Services Research. DOI: 10.1186/s12913-024-10716-7 
$^*$These authors contributed equally.

-  Carvalho-Pereira, T., Eyre, M., Zeppelini, C., Espirito Santo, V., Santiago, D., Santana, R., Palma, F., Reis, M., Lustosa, R., Khalil, H., Diggle, P., **<u>Giorgi, E.</u>**, Costa, F., Begon, M. (2023). *Basic urban services fail to neutralise environmental determinants of ‘rattiness’, a composite metric of rat abundance.* Urban Ecosystems. https://doi.org/10.1007/s11252-023-01481-2

-  Sasanami, M., Amoah, B., Amza, A., Souley, A. S. Y, Diori, A. N., Bakhtiari, A., Kadri, B., Szwarcwald, C. L., Gomez, D. V. F., Almou, I., Lopes, M. F. C., Masika, M. P., Beidou, N., Boyd, S., Harding-Esch, E. M., Solomon, A. W,  **<u>Giorgi, E.</u>** (2023). *Using model-based geostatistics for assessing the elimination of trachoma.* PLoS Neglected Tropical Diseases, 17(7): e0011476. https://doi.org/10.1371/journal.pntd.0011476

-  Dermauw, V., De Vijver, E. V., Dorny, P., **<u>Giorgi, E.</u>**, Ganaba, R., Millogo, A., Tarnagda, Z., Cisse, A. K., Carabin, A., *Geostatistical analysis of active human cysticercosis: Results of a large-scale study in 60 villages in Burkina Faso'.* PLoS Neglected Tropical Diseases.   https://doi.org/10.1371/journal.pntd.0011437


-  Borlase, A., Rutte, E. A., Castano, S., Blok, D. J., Toor, J., Giardina, F., Davis, E. L., NTD Consortium$^*$ (2022) *Evaluating and mitigating the potential indirect effect of COVID-19 on control programmes for seven neglected tropical diseases: a modelling study.* Lancet Global Health. DOI:10.1016/S2214-109X(22)00360-6 
 
$^*$ I have co-authored this paper as member of the NTD consortium.

-  Cremonese, C.,  Souza, F. N.,Palma, F. A. G., Sodre, J. F. A.,  Ribeiro, P. de S., Santana, J. O., Coelho, R. H., Ticona, J. P. A.,  Nazare, R., de Oliveira, D.,  Eyre, M., Knee, J., Ristow, P., Stauber, C.,  Lopez, Y. A., **<u>Giorgi, E.</u>**, Diggle, P. J., Cumming, O., dos Reis, M. G., Ko, A., Costa, F. (2023). *Simplified sewerage to prevent urban leptospirosis transmission: a cluster non-randomized controlled trial protocol in disadvantaged urban communities of Salvador, Brazil.* BMJ Open. 13:e065009. doi: 10.1136/bmjopen-2022-065009

-  Kitawa, Y. S., Johnson, O., **<u>Giorgi, E.</u>**, Zeytu Gashaw Asfaw (2023). Understanding the importance of spatial correlation in identifying spatio-temporal variation of disease risk, in the case of malaria risk mapping in southern Ethiopia. Scientific African. doi: 10.1016/j.sciaf.2023.e01926

-  Greenland-Bews, C., Byrne, R. L., Owen, S. O., Watkins, R. L., Bengey, D., Buist, K., Clerkin, K., Escadafal, C., Finch, L. S., Gould, S., **<u>Giorgi, E.</u>**, Hodgkinson, A., Mashenko, L., Powell, D., Savage, H. R,. Thompson, C. R., Turtle, L. T., Wardale, J., Wooding, D., Edwards, T., Atienzar, A. C. (2023). *Evaluation of Eight Lateral Flow Tests for the detection of anti-SARS-CoV-2 antibodies in a vaccinated population
Corresponding Author: Dr Emily R Adams.* BMC Infectious Diseases.  https://doi.org/10.1186/s12879-023-08033-1

-  Echodu, D., Yeka, D., Eganyu, T., Odude, W., Bukenya, F., Amoah, B., Wanzira, H., Colborn, K., Elliott, R. C., Powell, S. E., Kilama, M., Mulebeke, R., Nankabirwa, J., **<u>Giorgi, E.</u>**, Roskosky, M., Omoding, O., Gonahasa, S., Opigo, J. (2023). *Impact of population based indoor residual
spraying with and without mass drug
administration with dihydroartemisinin-piperaquine on malaria prevalence in a high transmission setting: a
controlled trial in northeastern Uganda.* BMC Infectious Diseases.  https://doi.org/10.1186/s12879-023-07991-w

-  Macharia, P. M., Moturi, A., Mumo, E., **<u>Giorgi, E.</u>**, Okiro, E. A., Snow, R. W., N. R. (2022). *Modelling geographic access and catchment areas for public primary schools in Kenya.* Children's Geographies.  https://doi.org/10.1080/14733285.2022.2137388


-  Eyre, M. T., Souza, F. N., Carvalho-Pereira, T. S. A., Nery, N., de Oliveira, D., Cruz, J. S., Sacramento, G. A., Khalil, H., Wunder, E. A., Hacker, K. P., Childs, J. E., Reis, M., Begon, M., Diggle, P. J., Ko, A. I., **<u>Giorgi, E.</u>**$^*$, Costa, F.$^*$ (2022). *Linking rattiness, geography and environmental
degradation to spillover Leptospira infections in marginalised urban settings.* ELife.  https://doi.org/10.7554/eLife.73120  
$^*$These authors contributed equally.


-  Ringwald, B., Tolhurst, R., Taegtmeyer, M., Digolo, L., Gichuna, G., Gaitho, M. M., Phillips-Howard, P. A., Otiso, L., **<u>Giorgi, E.</u>** (2022). *Intra-urban variation of intimate partner violence against women and men in Kenya: a secondary data analysis.* Journal of Interpersonal Violence. https://doi.org/10.1177/08862605221120893


-  Grau-Pujol, B., Cano, J., Marti-Soler, H., Casellas, A., **<u>Giorgi, E.</u>**, Nhacolo, A., Saute, F., Gine, R, Quinto, L., Sacoor, C., Munoz, J. (2022). *Neighbors' use of water and sanitation facilities can affect children's health: a cohort study in Mozambique using a spatial approach.* BMC Public Health 22, 983 (2022). https://doi.org/10.1186/s12889-022-13373-9

-  Kay, G. A., Owen, S. I., **<u>Giorgi, E.</u>**, Williams1, C. T., Menzies, S., Clark, D. J., Cuevas, L. C., Davies, B. M. O., Eckersley, N. M., Hughes, G. L., Kirwan, D. E., Krishna, S., Patterson, E. I., Planche, T., Staines, H. M., Adams, E. R. (2022). *Immunoglobulin-G enzyme-linked immunosorbent assay predicts neutralising antibody response in convalescent SARS-CoV-2 patients.* Scientific Reports.  3351 https://doi.org/10.1038/s41598-022-07263-8

-  Johnson, O., **<u>Giorgi, E.</u>**, Fronterre, C., Amoah, B., Atsame, J., Ella, S. N., Biamonte, M. Ogoussan, K., Hundley, L., Gass, K., Diggle, P. J. (2022). *Geostatistical modelling enables efficient safety assessment for ivermectin use in Loa loa endemic areas through a combined antibody and LoaScope testing strategy.* PLoS Neglected Tropical Diseases. 16, 2, p. e0010189



-  **<u>Giorgi, E.</u>**, Macharia, P. M., Woodmansey, J., Snow, R. W., Rowlingson, B. (2021). *Maplaria: a user friendly web-application for spatio-temporal malaria prevalence mapping.* Malaria Journal. 20, 471 https://doi.org/10.1186/s12936-021-04011-7


-  Amoah, B., McCann, R. S., Kabaghe, A. N., Mburu, M., Chipeta, M G., Moraga, P., Gowelo, S., Tizifa, T., van den Berg, H., Mzilahowa, T., Takken, W., van Vugt, M., Phiri, K.S., Diggle, P. J., Terlouw, D. J., **<u>Giorgi, E.</u>** (2021). *Identifying fine-scale spatiotemporal patterns in Plasmodium falciparum transmission by monitoring parasite  prevalence and entomological inoculation rate.* ELife. 10:e65682 doi:10.7554/eLife.65682


-  Grau-Pujol, B., Mart\`i-Soler, H., Escola, V., Demontis, V., Jamine, J. C., Gandasegui, J., Muchisse, O., Cambra-Pellej\'a, M., Cossa, A., Martinez-Valladares, M., Sacoor, C., Van Lieshout, L., Cano, J.,  **<u>Giorgi, E.</u>**, Munoz, J. (2021). *Towards soil-transmitted helminths transmission interruption: the impact of diagnostic tools on infection prediction in a low intensity setting in Southern Mozambique.* PLoS Neglected Tropical Diseases.   https://doi.org/10.1371/journal.pntd.0009803

-  Aguilar Ticona, J. P., Nery, N., Victoriano, R., Fofana, M. O., Ribeiro, G. S.,**<u>Giorgi, E.</u>**, Reis, M. G., Ko, A. I., Costa, F. (2021). *Willingness to get the COVID-19 vaccine among residents of slum
settlements.* Vaccines. 2021, 9(9), 951; https://doi.org/10.3390/vaccines9090951

-  Dissanayake, R., **<u>Giorgi, E.</u>**, Stevenson, M., Allavena, R., Henning, J. (2021). *Estimating koala density from incidental koala sightings in South-East Queensland, Australia (1997–2013), using a self-exciting spatio-temporal point process model* Ecology and Evolution. DOI: 10.1002/ece3.8082

-  Amoah, B., Fronterre, C., Johnson, O., Dejene, M., Seife, F., Negussu, N., Bakhtiari, A., Harding-Esch, E., **<u>Giorgi, E.</u>**, Solomon, A. W., Diggle, P. J. (2021). *Geostatistical analysis can yield more precise neglected tropical disease prevalence estimates than traditional analysis methods: mapping trachoma prevalence in Ethiopia.* International Journal of Epidemiology. dyab227, https://doi.org/10.1093/ije/dyab227


-  Macharia, P. M., Ray, N., **<u>Giorgi, E.</u>**, Okiro, E. A., Snow, R. W. (2021). *Defining service catchment areas in low resource settings.* BMJ Global Health. http://dx.doi.org/10.1136/bmjgh-2021-006381


-  Toor, J., Adams, E. R., Aliee, M., Amoah, B., Anderson, R. M., Ayabina, D., Bailey, R., Basanez, M.-G., Blok, D. J.,  Blumberg, S., Borlase, A., Rivera, R. C., Castano, M. S, Chitnis, N., Coffeng, L. E., Crump, R. E., Das, A., Davis, C. N., Davis, E. L., Deiner, M. S., Diggle, P. J., Fronterre, C., Giardina, F., **<u>Giorgi, E.</u>**, Graham, R., Hamley, J. I. D., Huang, C.-I., Kura, K., Lietman, T. M., Lucas, T. C. D., Malizia, V., Medley, G. F., Meeyai, A., Michael, E., Porco, T., Prada, J. M., Rock, K. T. S.,Le Rutte, E., Smith, M. E., Spencer, S. E. F., Stolk, W. A., Touloupou, P., Vasconcelos, A., Vegvari, C., de Vlas, S. J., Walker, M.,  Hollingsworth, T. D. (2021) *Predicted Impact of COVID-19 on Neglected Tropical Disease Programs and the Opportunity for Innovation, Clinical Infectious Diseases*,  https://doi.org/10.1093/cid/ciaa933

-  Johnson, O. O., Fronterre, C., Amoah, A., Montresor, A.,  **<u>Giorgi, E.</u>**, Midzic, N., Mutsaka-Makuvaza, M. J., Kargbo-Labord, I., Hodgese, M. H, Zhange, Y., Okoyog, C., Mwandawirog, C., Minnery, M., Digglea, P. J., *Model-based Geostatistical Methods Enable Efficient Design and Analysis of Prevalence Surveys for Soil-Transmitted Helminth Infection and Other Neglected Tropical Disease.* Clinical Infectious Diseases. 2021;72(S3):S172–9, DOI: 10.1093/cid/ciab192

-  Savage, E. R., Santos, V. S., Edwards, T.,  **<u>Giorgi, E.</u>**, Krishna, S., Planche, T., Staines, H. M., Fitchett, J. R. A.,  Kirwan, D. E.,  Atienzar, A. I. E.,  Clark, D. J.,, Adams, E. R., Cueva, L. E. *Prevalence of neutralising antibodies against SARS-CoV-2 in acute infection and convalescence: a systematic review and meta-analysis*. Plos Neglected Tropical Diseases.   https://doi.org/10.1371/journal.pntd.0009551


-  Diggle, P. J., Amoah, B., Claudio, F.,  **<u>Giorgi, E.</u>**, Johnson, O. O. (2021) *Rethinking NTD Prevalence Survey Design and Analysis: a Geospatial Paradigm.* Transactions of the Royal Society of Tropical Medicine and Hygiene. Pages 208–210, https://doi.org/10.1093/trstmh/trab020

-  Andreis, F., Bryant, R., **<u>Giorgi, E.</u>**, Williamson, A. E., Ward. A. (2021) *Prescribing patterns for medical treatment of suspected prostatic obstruction: a longitudinal register-based study of the Scottish Health and Social Care Open Data* BMJ Open. doi:10.1136/bmjopen-2020-042606

-  Hossain, E., Hoque, A., **<u>Giorgi, E.</u>**, Fournie, G., Das, G. B., Henning, J. (2021). *Impact of improved small-scale livestock farming on human nutrition.* Scientific Reports. doi:10.1038/s41598-020-80387-x


-  Moirano, G., Zanet, S., **<u>Giorgi, E.</u>**, Battisti, E., Falzoi, S., Acquaotta, F.,  Fratianni, S., Richiardi, L., Maule, M., Ferroglio, E. (2020) *Integrating environmental, entomological, animal and human data to model the Leishmania infantum transmission risk in a new endemic area in Northern Italy.* One Health. doi:10.1016/j.onehlt.2020.100159


-  Deribe, K., Florence, L., Kelemework, A., Getaneh, T., Tsegay, G., Cano, J., **<u>Giorgi, E.</u>**, Newport, M. J., Davey,G. (2020) *Developing and validating a clinical algorithm for the diagnosis of podoconiosis.* Transactions of the Royal Society of Tropical Medicine and Hygiene.   doi:10.1093/trstmh/traa074

-  Stockdale, A. J., Kreuels, B., Henrion, M. Y. R., **<u>Giorgi, E.</u>**, Kyomuhangi, I., de Martel, C., Hutin, Y., Geretti, A. M. (2020). *The global prevalence of hepatitis D virus infection: systematic review and meta-analysis.* Journal of Hepatology. PMID: 32335166  DOI: 10.1016/j.jhep.2020.04.008

-  Kigozi, S. P., **<u>Giorgi, E.</u>**, Mpimbaza, A., Kigozi, R. N., Bousema, T., Arinaitwe, E., Nankabirwa, J. I., Sebuguzi, C. M., Kamya, M. R., Staedke, S. G., Dorsey, G., Pullan, R. L. (2020). *Practical implications of a relationship between Health Management Information System and community cohort-based malaria incidence rates.* American Journal of Tropical Medicine and Hygiene. doi: 10.4269/ajtmh.19-0950.  




-  Runge, M., Snow, R. W.,  Molteni, F., Thawer, S., Mohamed, A., Mandike, R., **<u>Giorgi, E.</u>**, Macharia, P. M., Smith, T., Lengeler, C., Pothin, E., (2020). *Simulating the council-specific impact of anti-malaria interventions: a tool to support malaria strategic planning in Tanzania.* Malaria Journal. https://doi.org/10.1371/journal.pone.0228469




-  Neyens, T., Diggle, P. D., Faes, C., Beenaerts, N., Artois, T., **<u>Giorgi, E.</u>** (2020). *Mapping species richness using opportunistic samples: a case study on ground-floor bryophyte species richness in the Belgian province of Limburg.* Scientific Reports 9, 19122, doi:10.1038/s41598-019-55593-x

-  Hale, A. C., S\'anchez-Vizca\'ino, F., Rowlingson, B., Radford, A. D., **<u>Giorgi, E.</u>**, O’Brien, S. J., Diggle, P. J. (2019). *A real-time spatio-temporal syndromic surveillance system with application to small companion animals.* Scientific Reports 9, 17738, doi:10.1038/s41598-019-53352-6

-  Nightingale, R., Mortimer, K., **<u>Giorgi, E.</u>**, Walker, P., Stolbrink, M., Byrne, T., Marwood, K., Morrison-Griffiths, S., Renwick, S., Rylance, J., Burhan, H., (2019). *Screening heroin smokers attending community drug clinics for change in lung function: A cohort study.* Chest.   doi:10.1016/j.chest.2019.11.006



-  Diggle, P. J., **<u>Giorgi, E.</u>**, Atsame, J., Ella, S. N., Ogoussan, K., Gass, K. (2020). *A tale of two parasites: statistical modelling to support disease control programmes in Africa.* Statistical Science. 35:42-50, doi:10.1214/19-STS738

-  Flueckiger, R., **<u>Giorgi, E.</u>**, Cano, J., Abdala, M., Amiel, O. N., Baayenda, G., Bakhtiari, A., Batcho, W., Bennawi, K. H., Dejene, M., Elshafie, B. E., Elvis, A. A.,  Francois, M., Goepogui, A., Kalua, K., Kebede, B., Kiflu, G., Masika, M. P., Massangaie, M., Mpyet, C., Ndjemba, J., Ngondi, J. M., Olobio, N., Turyaguma, P., Willis, R., Yeo, S., Solomon, A., Pullan, R. (2019). *Understanding the spatial distribution of trichiasis and its association with trachomatous inflammation—follicular*. BMC Infectious Diseases, 19:364, doi:10.1186/s12879-019-3935-1

-  Chipeta, M. G., **<u>Giorgi, E.</u>**, Mategula, D., Macharia, P. M., Ligomba1, C., Munyenyembe, A., Chirombo, J., Gumbo, A., Terlouw, D. J., Snow, R. W., Kayange, M. (2019). *Geostatistical analysis of Malawi’s changing malaria transmission from 2010 to 2017.* Wellcome Open Research, 4:57, doi:10.12688/wellcomeopenres.15193.1

-  Deribe, K., Mbituyumuremyi, A., Cano, J., Bosco, M. J., **<u>Giorgi, E.</u>**, Ruberanziza, E., Bayisenge, U., Leonard, U., Bikorimana, J. P., Rucogoza, A., Turate, I., Rusanganwa, A., Pigott, D. M., Pullan, R. L., Noor, A. M., Enquselassie, F., Condo, J. U., Murray, C. J. L.,  Brooker, S. J., Hay, S. I., Newport, M. J., Davey, G. (2019). *Geographical Distribution and Prevalence of Podoconiosis in Rwanda: A Cluster Cross-Sectional Country-wide Survey*. Lancet Global Health. DOI:10.1016/S2214-109X(19)30072-5

-  Macharia, P., **<u>Giorgi, E.</u>**, Thuranira, P. N., Joseph, N. K., Sartorius, B., Snow, R. W., Okiro, E. A. (2019). *Sub national variation and inequalities in under-five mortality in Kenya since 1965.* BMC Global Health. 19:146, doi:10.1186/s12889-019-6474-1

-  Macharia, P., **<u>Giorgi, E.</u>**, Noor, A., Waqo, E., Kiptui, R., Okiro, E., Snow, R. (2018). *Spatio-temporal analysis of Plasmodium falciparum prevalence to understand the past and chart the future of malaria control in Kenya*. Malaria journal. 26;17(1):340. doi: 10.1186/s12936-018-2489-9.

-   McCann, R. S., van den Berg, H., Takken, W., Chetwynd, A. G., **<u>Giorgi, E.</u>**, Terlouw, D. J., Diggle, P. J. (2018). *Reducing contamination risk in cluster-randomised infectious disease intervention trials.* International Journal of Epidemiology. dyy213, https://doi.org/10.1093/ije/dyy213

-   Stresman, G., Mwesigwa, J., Achan, J., **<u>Giorgi, E.</u>**, Worwui, A., Jawara, M., di Tanna, G., Bousema, T., Van Geertruyden, J.-P., Drakeley, C., D'Alessandro, U. (2018). *Do high burden households fuel malaria transmission? A village-scale spatio-temporal analysis of a two-year cohort study in The Gambia.* BMC Medicine. https://doi.org/10.1186/s12916-018-1141-4


-  Deribe, D., Cano, J., Njouendou, A. J., Eyong, M. E., Beng, A. A., **<u>Giorgi, E.</u>**, Pigott, D. M., Pullan, R. L., Noor, A. M., Enquselassie, F., Murray, C. J. L., Hay, S. I., Newport, M. J., Davey, G., Wanji, S. (2018). *Predicted distribution and burden of podoconiosis in Cameroon.* BMJ Global Health; 3:e000730.
 
-  Wanji, S., Kengne-Ouafo, J. A., Deribe, K., Tambei, A. M., Njouendou, A. J., Tayong, D. B., Datchoua-Poutcheu, F. R., Sofeu-Feugaing, D. D., Cano, J., **<u>Giorgi, E.</u>**, Longang-Tchounkeu, Y. F., Enyong, P. A., Newport, M. J., Davey, G. (2018). *Study of Lymphoedema of Non-Filarial Origin in the North West Region of Cameroon: Spatial Distribution, Profiling of Cases and Socio-economic Aspects of Podoconiosis.* International Health.  ihy028,   https://doi.org/10.1093/inthealth/ihy028

-  Colborn, K.,  **<u>Giorgi, E.</u>**, Monaghan, A., Gudo, E., Candrinho, B., Marrufo, T., Colborn, J. (2018). *Spatio-temporal modelling of weekly malaria incidence in children under 5 for early epidemic detection in Mozambique.* Scientific Reports. 8, 9238, doi.org/10.1038/s41598-018-27537-4

-  Amoah, B., **<u>Giorgi, E.</u>**, Hayes, D., van Buuren, S., Diggle, P. J. (2018). *Geostatistical modelling of the relationship between malaria and child growth in Africa.* International Journal of Health Geographics. 17:7,
https://doi.org/10.1186/s12942-018-0127-y 


-  **<u>Giorgi, E.</u>**, Osman, A. A., Hassan, A. H., Ali, A. A., Ibrahim, F., Amran, J. G. H., Noor, A. M., Snow, R. W. (2018). *Using non-exceedance probabilities of policy-relevant malaria prevalence thresholds to identify areas of low transmission in Somalia.* Malaria Journal. 17:88,  
https://doi.org/10.1186/s12936-018-2238-0 

-  Deribe, K., Mbeng, A. A., Cano, J., Njouendo, A. J., Fru-Cho, J., Abong, R., Eyong, M. E., Ndongmo, P. W. C, **<u>Giorgi, E.</u>**, Pigott, D. M., Golding, N. et al. (2017). *Mapping the geographical distribution of podoconiosis in Cameroon using parasitological, serological, and clinical evidence to exclude other causes of lymphedema.* PLOS Neglrected Tropical Diseases 12(1): e0006126.   https://doi.org/10.1371/journal.pntd.0006126

-  Jary , H. R., Aston, S., Ho, A., **<u>Giorgi, E.</u>**, Kalata, N., Nyirenda, M., Mallewa, J., Peterson, I., Gordon, S. B., Mortimer, K. (2017). *Household air pollution and pneumonia in Malawian adults: a case-control study.* Wellcome Open Research, 2:103, doi: 10.12688/wellcomeopenres.12621.1

-  Henning, J., **<u>Giorgi, E.</u>**, Soares Magalh\~aes, R. J., Tizzani, P., Viviani, P., Pejovic, N., Hrapovi\'c, M., Potzsch, C. (2017). *Factors influencing the success of aerial rabies vaccination of foxes.* Scientific Reports.  7,  14376, doi:10.1038/s41598-017-14615-2


-  Deribe, K., Cano, J., **<u>Giorgi, E.</u>**, Pigott, D., Golding, N., Pullan, R. L., Noor, A. M., Cromwell, E. A., Osgood‐Zimmerman, A.,  Enquselassie, F., Hailu, A., Murray, C. J. L., Newport, M. J., Brooker, S. J.,  Hay, S. I., Davey, G. (2017). *Estimating the number of cases of podoconiosis in Ethiopia using geostatistical methods.* Wellcome Open Research, 2:78. doi: 10.12688/wellcomeopenres.12483.1

-  Sesay, S. S., **<u>Giorgi, E.</u>**, Diggle, P. J., Schellenberg, D., Lalloo, D. G., Terlouw, D. J. (2017). *Surveillance in easy to access population subgroups as a tool for evaluating malaria control progress: a systematic review.* PLOS ONE 12(8):  
e0183330. https://doi.org/10.1371/journal.pone.0183330

-  McCann, R. S., Messina, J. P, MacFarlane, D. W., Bayoh, M. N., Gimnig, J. E., **<u>Giorgi, E.</u>**, Walker, E. D. (2017). *Explaining variation in adult Anopheles indoor resting abundance: the relative effects of larval habitat proximity and insecticide-treated bed net use.* Malaria journal. 16:288, DOI:10.1186/s12936-017-1938-1


-  Stresman, G., **<u>Giorgi, E.</u>**, Baidjoe, A., Knight, P., Odongo, W., Owaga, C., Shagari, S., Makori, E., Stevenson, J., Drakeley, C., Cox, J., Bousema, T., Diggle, P. J. (2017). *Impact of metric, sample size and geostatistical methods on determining boundaries of hotspots of malaria.* Scientific Reports. 7, 45849; doi: 10.1038/srep45849

-  **<u>Giorgi, E.</u>**, Kreppel, K., Diggle, P. J., Maherisoa, R., Minoarisoa, R., Caminade, C., Baylis, M. (2016). *Modelling of spatio-temporal variation in plague incidence in Madagascar from 1980 to 2007.* Spatial and Spatio-temporal Epidemiology. 19:125-135

-  Ediriweera, D. S., Kasturiratne, A., Pathmeswaran, A., Gunawardena, N. K., Wijayawickrama, B. A., Jayamanne, S. F., Isbister, G. K., Dawson, A., **<u>Giorgi, E.</u>**, Diggle, P. J., Lalloo, D. G., de Silva, H. J. (2016). *Mapping the Risk of Snakebite in Sri Lanka- A National Survey with Geospatial Analysis.* PLoS Neglected Tropical Diseases. 10(7): e0004813. doi: 10.1371/journal.pntd.0004813


-  Zoure, H. G. M., Noma, M., Tekle, A. H., Amazigo, U. V., Diggle, P. J., **<u>Giorgi, E.</u>**, Remme, J. H. F. (2014). *The Geographic Distribution of Onchocerciasis in the 20 Participating Countries of the African Programme for Onchocerciasis Control.* Parasites and Vectors. 7:326, doi:10.1186/1756-3305-7-326

-  Bosco, E., Marton, E., Feletti, A., Scarpa, B., Longatti, P., Zanatta, P., **<u>Giorgi, E.</u>**, Sorbara, C. (2011). *Dynamic monitors of brain function: a new target in neurointensive care unit.* Critical Care, 15:R170

## Teaching of Statistics {#teaching}

-  Johnson, O., Fronterre, C., Diggle, P. J., Amoah, A.,  **<u>Giorgi, E.</u>** (2021). *MBGapp: A Shiny application for teaching model-based geostatistics to population health scientists.* PLoS ONE. https://doi.org/10.1371/journal.pone.0262145

-  **<u>Giorgi, E.</u>** (2018). *Using a problem-driven approach for teaching statistics at the African Institute of Mathematical Sciences (invited paper).* In M. A. Sorto, A. White, & L. Guyot (Eds.), Looking back, looking forward. Proceedings of the
Tenth International Conference on Teaching Statistics (ICOTS10, July, 2018), Kyoto, Japan. Voorburg, The Netherlands: International Statistical Institute.  Available [here](https://iase-web.org/icots/10/proceedings/pdfs/ICOTS10_3H3.pdf?1531364259)
